---
os: linux
dist: xenial
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-9
matrix:
  allow_failures:
    - rvm: jruby-9
before_install: gem install bundler --version 1.17.3
